class Autogenerated {
  int id;
  String name;
  String doctor;
  String nywc;
  String time;
  String task;

  Autogenerated(
      {this.id, this.name, this.doctor, this.nywc, this.time, this.task});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    doctor = json['doctor'];
    nywc = json['nywc'];
    time = json['time'];
    task = json['task'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['doctor'] = this.doctor;
    data['nywc'] = this.nywc;
    data['time'] = this.time;
    data['task'] = this.task;
    return data;
  }
}