import 'package:doctorapp/Model/userclass.dart';
import 'package:doctorapp/service/service.dart';
import 'package:flutter/material.dart';

class Futerbuilder extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
return FutureBuilder<List<Autogenerated>>(
  future: fetchJSONData(),
  builder: (context, snapshot) {
    if (!snapshot.hasData)
      return Center(child: CircularProgressIndicator());

    return ListView(
      children: snapshot.data
          .map(
            (user) => ListTile(
          title: Container(
            child: Column(
              children: [
                Card(
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15)
                  ),
                  color: Colors.white,
                  child: ListTile(
                    leading: Icon(
                      Icons.flag,
                      color: Colors.green,
                    ),
                    title: Text(user.name),
                    subtitle: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(user.doctor),
                        Text(user.nywc),
                      ],
                    ),
                    trailing: Column(
                      crossAxisAlignment: CrossAxisAlignment.end,
                      children: [
                        Text(user.time),
                        SizedBox(height: 5,),
                        Text(user.task),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      )
          .toList(),
    );
  },
);
  }

}